#!/usr/bin/env python3
"""
Extract the analytics schema from a real tenant and emit Demo's DDL.

Structure drift between Demo and the client schema is impossible if the DDL is
read rather than written: this connects read-only to the source tenant, reads
INFORMATION_SCHEMA.COLUMNS for the manifest in demo_config.REPLICATED_TABLES,
and writes:

    scripts/demo/create_demo_schema.sql   -- run this against the Demo DB
    scripts/demo/schema_snapshot.json     -- column/type map the seeder loads

The V4_* objects are views in the source DB; nothing in the app writes to them,
so Demo gets them as plain tables and the seeder populates them directly.
INFORMATION_SCHEMA covers views and tables identically, so no special case is
needed here.

Only structure is read. No data.

Usage:
    python scripts/demo/extract_schema.py                 # from nhs
    python scripts/demo/extract_schema.py --tenant ohs
"""

import argparse
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, ROOT)
sys.path.insert(0, HERE)

import demo_config as C   # noqa: E402

SQL_OUT      = os.path.join(HERE, 'create_demo_schema.sql')
SNAPSHOT_OUT = os.path.join(HERE, 'schema_snapshot.json')

# Types whose declaration carries a length.
LEN_TYPES   = {'char', 'varchar', 'nchar', 'nvarchar', 'binary', 'varbinary'}
# Types whose declaration carries precision/scale.
PREC_TYPES  = {'decimal', 'numeric'}
# Types whose declaration carries fractional-seconds precision.
SCALE_TYPES = {'datetime2', 'datetimeoffset', 'time'}


def render_type(col):
    """Render a SQL Server type declaration from an INFORMATION_SCHEMA row."""
    t = col['data_type'].lower()
    if t in LEN_TYPES:
        n = col['char_max_len']
        size = 'MAX' if n in (-1, None) else str(n)
        return f'{t.upper()}({size})'
    if t in PREC_TYPES:
        return f"{t.upper()}({col['num_precision']}, {col['num_scale']})"
    if t in SCALE_TYPES and col['datetime_precision'] is not None:
        return f"{t.upper()}({col['datetime_precision']})"
    return t.upper()


def extract(tenant):
    import pyodbc
    from dotenv import load_dotenv
    load_dotenv()
    from pipeline_config import get_tenant_config, get_db_params

    cfg = get_tenant_config(tenant)
    server, database, user, password = get_db_params(cfg)
    conn = pyodbc.connect(
        C.odbc_connection_string(server, database, user, password),
        timeout=60, readonly=True,
    )
    print(f'  Connected read-only to {server} / {database}')

    cur = conn.cursor()
    placeholders = ', '.join('?' * len(C.REPLICATED_TABLES))
    cur.execute(f"""
        SELECT TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, DATA_TYPE,
               CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE,
               DATETIME_PRECISION, IS_NULLABLE
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME IN ({placeholders})
        ORDER BY TABLE_NAME, ORDINAL_POSITION
    """, *C.REPLICATED_TABLES)

    tables = {}
    for (tbl, col, pos, dtype, clen, prec, scale, dtprec, nullable) in cur.fetchall():
        tables.setdefault(tbl, []).append({
            'name': col,
            'ordinal': int(pos),
            'data_type': dtype,
            'char_max_len': clen,
            'num_precision': prec,
            'num_scale': scale,
            'datetime_precision': dtprec,
            'nullable': nullable == 'YES',
        })
    conn.close()

    missing = [t for t in C.REPLICATED_TABLES if t not in tables]
    if missing:
        print(f'  WARNING: not found in {database}: {", ".join(missing)}')
    for t, cols in tables.items():
        print(f'  {t:34s} {len(cols):3d} columns')
    return tables, database


def render_sql(tables, source_db, tenant):
    stamp = datetime.datetime.now().isoformat(timespec='seconds')
    lines = [
        '-- Demo tenant schema — Bright Memorial Health',
        '--',
        f'-- Generated by scripts/demo/extract_schema.py on {stamp}',
        f'-- Structure extracted from tenant "{tenant}" (database {source_db}).',
        '-- Structure only: no data, no constraints, no client content.',
        '--',
        '-- Run this against the empty Demo database. Re-running drops and',
        '-- recreates every table, so it is safe to repeat while iterating.',
        '',
    ]
    for tbl in C.REPLICATED_TABLES:
        cols = tables.get(tbl)
        if not cols:
            lines += [f'-- !! {tbl} was not found in the source database — skipped.', '']
            continue
        lines += [
            f"IF OBJECT_ID('dbo.{tbl}', 'U') IS NOT NULL DROP TABLE dbo.{tbl};",
            f'CREATE TABLE dbo.{tbl} (',
        ]
        width = max(len(c['name']) for c in cols) + 2
        body = []
        for c in cols:
            null = 'NULL' if c['nullable'] else 'NOT NULL'
            body.append(f"    [{c['name']}]{' ' * (width - len(c['name']))}{render_type(c)} {null}")
        lines.append(',\n'.join(body))
        lines += [');', '']

        # An index on the column the app filters on most often for this table.
        idx_col = {
            'DS_CASES':                      'Date_SchedDate',
            'DS_Encounters':                 'TIME_HOSPDISCHARGE',
            'DS_Bedplacement':               'TIME_REQUESTTIME',
            'DS_Occupancy':                  'Datehour',
            'DS_RR':                         'rrDate',
            'V4_BlockResultsView':           'BlockDate',
            'V4_FORECAST_COMPILE':           'Date',
            'V4_Inpatient_Forecast_Compile': None,
        }.get(tbl)
        if idx_col and any(c['name'].lower() == idx_col.lower() for c in cols):
            lines += [
                f'CREATE INDEX IX_{tbl}_{idx_col} ON dbo.{tbl} ([{idx_col}]);',
                '',
            ]

    lines += [
        '-- ── Demo-first tables (DemoTenant.md 5.2) ─────────────────────────────────',
        '-- Not present in client databases yet; they arrive there when the ISSCM',
        '-- features go live.',
        C.NEW_TABLE_DDL.strip(),
        '',
    ]
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser(description='Extract Demo DDL from a source tenant.')
    ap.add_argument('--tenant', default='nhs', help='source tenant (default: nhs)')
    ap.add_argument('--sql-out', default=SQL_OUT)
    ap.add_argument('--snapshot-out', default=SNAPSHOT_OUT)
    args = ap.parse_args()

    tables, source_db = extract(args.tenant)

    with open(args.sql_out, 'w', encoding='utf-8') as fh:
        fh.write(render_sql(tables, source_db, args.tenant))
    with open(args.snapshot_out, 'w', encoding='utf-8') as fh:
        json.dump({
            'source_tenant': args.tenant,
            'source_database': source_db,
            'generated_at': datetime.datetime.now().isoformat(timespec='seconds'),
            'tables': tables,
        }, fh, indent=2)
        fh.write('\n')

    print(f'\n  Wrote {args.sql_out}')
    print(f'  Wrote {args.snapshot_out}')
    print('  Review the SQL, then run it against the Demo database.')


if __name__ == '__main__':
    main()
